permalink: /:month-:day-:year/:title.html

# Theme settings
theme:

  # Site name
  site_name: FRNK

  # Google analytics UID
  google_analytics_uid: 

  # Disqus shortname, for comments
  disqus_shortname: frnk-blog

  # Number of featured posts on homepage
  homepage_featured: 1

  # Number of posts on homepage (in addition to featured posts)
  homepage_posts: 2

  # Number of words to display in post summaries
  featured_wordcount: 20

author :
  name : Franco Fallica
  email : franco.fallica@gmail.com
  github : hanken
  twitter : francenhanken
  feedname : frnk

